// Code generated by cxgo. DO NOT EDIT.

package vectrace

import (
	"fmt"
	"io"
	"strings"
	"unsafe"
)

func unitD(info *RenderConf, p DPoint) DPoint {
	return DPoint{X: p.X * info.Unit, Y: p.Y * info.Unit}
}

type svgContext struct {
	out     io.Writer
	cur     DPoint
	lastop  int8
	column  int
	newline int
}

func (ctx *svgContext) shiptoken(token string) {
	var c int = len(token)
	if ctx.newline == 0 && ctx.column+c+1 > 75 {
		fmt.Fprint(ctx.out, "\n")
		ctx.column = 0
		ctx.newline = 1
	} else if ctx.newline == 0 {
		fmt.Fprint(ctx.out, " ")
		ctx.column++
	}
	fmt.Fprint(ctx.out, token)
	ctx.column += c
	ctx.newline = 0
}

// ship は C の可変引数を Go のスライスで受け取るように簡略化
func (ctx *svgContext) ship(format string, args ...interface{}) {
	s := fmt.Sprintf(format, args...)
	// スペース区切りで shiptoken に渡す C のロジックを再現
	tokens := strings.Split(s, " ")
	for _, t := range tokens {
		ctx.shiptoken(t)
	}
}

func (ctx *svgContext) svg_moveto(info *RenderConf, p DPoint) {
	ctx.cur = unitD(info, p)
	ctx.ship("M%.2f %.2f", ctx.cur.X, ctx.cur.Y)
	ctx.lastop = 'M'
}
func (ctx *svgContext) svg_rmoveto(info *RenderConf, p DPoint) {
	var q DPoint
	q = unitD(info, p)
	ctx.ship("m%.2f %.2f", q.X-ctx.cur.X, q.Y-ctx.cur.Y)
	ctx.cur = q
	ctx.lastop = 'm'
}
func (ctx *svgContext) svg_lineto(info *RenderConf, p DPoint) {
	var q DPoint
	q = unitD(info, p)
	if int(ctx.lastop) != 'l' {
		ctx.ship("l%.2f %.2f", q.X-ctx.cur.X, q.Y-ctx.cur.Y)
	} else {
		ctx.ship("%.2f %.2f", q.X-ctx.cur.X, q.Y-ctx.cur.Y)
	}
	ctx.cur = q
	ctx.lastop = 'l'
}
func (ctx *svgContext) svg_curveto(info *RenderConf, p1 DPoint, p2 DPoint, p3 DPoint) {
	var (
		q1 DPoint
		q2 DPoint
		q3 DPoint
	)
	q1 = unitD(info, p1)
	q2 = unitD(info, p2)
	q3 = unitD(info, p3)
	if int(ctx.lastop) != 'c' {
		ctx.ship("c%.2f %.2f %.2f %.2f %.2f %.2f", q1.X-ctx.cur.X, q1.Y-ctx.cur.Y, q2.X-ctx.cur.X, q2.Y-ctx.cur.Y, q3.X-ctx.cur.X, q3.Y-ctx.cur.Y)
	} else {
		ctx.ship("%.2f %.2f %.2f %.2f %.2f %.2f", q1.X-ctx.cur.X, q1.Y-ctx.cur.Y, q2.X-ctx.cur.X, q2.Y-ctx.cur.Y, q3.X-ctx.cur.X, q3.Y-ctx.cur.Y)
	}
	ctx.cur = q3
	ctx.lastop = 'c'
}
func (ctx *svgContext) svg_path(info *RenderConf, curve *Curve, abs int) int {
	var (
		i int
		m int = curve.N
	)
	// unsafe ポインタ演算をスライスインデックスに置換
	if abs != 0 {
		ctx.svg_moveto(info, curve.C[m-1][2])
	} else {
		ctx.svg_rmoveto(info, curve.C[m-1][2])
	}
	for i = 0; i < m; i++ {
		switch curve.Tag[i] {
		case POTRACE_CORNER:
			ctx.svg_lineto(info, curve.C[i][1])
			ctx.svg_lineto(info, curve.C[i][2])
		case POTRACE_CURVETO:
			ctx.svg_curveto(info, curve.C[i][0], curve.C[i][1], curve.C[i][2])
		}
	}
	ctx.newline = 1
	ctx.shiptoken("z")
	return 0
}
func (ctx *svgContext) svg_jaggy_path(info *RenderConf, pt *Point, n int, abs int) int {
	var (
		i       int
		current Point
		prev    Point
	)
	// unsafe.Add をスライス操作に置き換え
	pts := unsafe.Slice(pt, n)
	if abs != 0 {
		prev = pts[n-1]
		current = prev
		ctx.svg_moveto(info, dpoint(current))
		for i = 0; i < n; i++ {
			if pts[i].X != current.X && pts[i].Y != current.Y {
				current = prev
				ctx.svg_lineto(info, dpoint(current))
			}
			prev = pts[i]
		}
		ctx.svg_lineto(info, dpoint(pts[n-1]))
	} else {
		prev = pts[0]
		current = prev
		ctx.svg_rmoveto(info, dpoint(current))
		for i = n - 1; i >= 0; i-- {
			if pts[i].X != current.X && pts[i].Y != current.Y {
				current = prev
				ctx.svg_lineto(info, dpoint(current))
			}
			prev = pts[i]
		}
		ctx.svg_lineto(info, dpoint(pts[0]))
	}
	ctx.newline = 1
	ctx.shiptoken("z")
	return 0
}
func (ctx *svgContext) write_paths_opaque(info *RenderConf, tree *Path) {
	var (
		p *Path
		q *Path
	)
	for p = tree; p != nil; p = p.Sibling {
		if info.Grouping == 2 {
			fmt.Fprint(ctx.out, "<g>\n<g>\n")
		}
		n, _ := fmt.Fprintf(ctx.out, "<path fill=\"#%06x\" stroke=\"#%06x\" stroke-width=\"%f\" stroke-linejoin=\"round\" d=\"", info.Color, info.Color, 0.5*info.Unit)
		ctx.column = n
		ctx.newline = 1
		ctx.lastop = 0
		if info.Debug {
			ctx.svg_jaggy_path(info, &p.Priv.Pt[0], p.Priv.Len, 1)
		} else {
			ctx.svg_path(info, &p.Curve, 1)
		}
		fmt.Fprint(ctx.out, "\"/>\n")
		for q = p.Childlist; q != nil; q = q.Sibling {
			n, _ := fmt.Fprintf(ctx.out, "<path fill=\"#%06x\" stroke=\"#%06x\" stroke-width=\"%f\" stroke-linejoin=\"round\" d=\"", info.Fillcolor, info.Fillcolor, 0.5*info.Unit)
			ctx.column = n
			ctx.newline = 1
			ctx.lastop = 0
			if info.Debug {
				ctx.svg_jaggy_path(info, &q.Priv.Pt[0], q.Priv.Len, 1)
			} else {
				ctx.svg_path(info, &q.Curve, 1)
			}
			fmt.Fprint(ctx.out, "\"/>\n")
		}
		if info.Grouping == 2 {
			fmt.Fprint(ctx.out, "</g>\n")
		}
		for q = p.Childlist; q != nil; q = q.Sibling {
			ctx.write_paths_opaque(info, q.Childlist)
		}
		if info.Grouping == 2 {
			fmt.Fprint(ctx.out, "</g>\n")
		}
	}
}
func (ctx *svgContext) write_paths_transparent_rec(info *RenderConf, tree *Path) {
	var (
		p *Path
		q *Path
	)
	for p = tree; p != nil; p = p.Sibling {
		if info.Grouping == 2 {
			fmt.Fprint(ctx.out, "<g>\n")
		}
		if info.Grouping != 0 {
			n, _ := fmt.Fprintf(ctx.out, "<path d=\"")
			ctx.column = n
			ctx.newline = 1
			ctx.lastop = 0
		}
		if info.Debug {
			ctx.svg_jaggy_path(info, &p.Priv.Pt[0], p.Priv.Len, 1)
		} else {
			ctx.svg_path(info, &p.Curve, 1)
		}
		for q = p.Childlist; q != nil; q = q.Sibling {
			if info.Debug {
				ctx.svg_jaggy_path(info, &q.Priv.Pt[0], q.Priv.Len, 0)
			} else {
				ctx.svg_path(info, &q.Curve, 0)
			}
		}
		if info.Grouping != 0 {
			fmt.Fprint(ctx.out, "\"/>\n")
		}
		for q = p.Childlist; q != nil; q = q.Sibling {
			ctx.write_paths_transparent_rec(info, q.Childlist)
		}
		if info.Grouping == 2 {
			fmt.Fprint(ctx.out, "</g>\n")
		}
	}
}
func (ctx *svgContext) write_paths_transparent(info *RenderConf, tree *Path) {
	if info.Grouping == 0 {
		n, _ := fmt.Fprintf(ctx.out, "<path d=\"")
		ctx.column = n
		ctx.newline = 1
		ctx.lastop = 0
	}
	ctx.write_paths_transparent_rec(info, tree)
	if info.Grouping == 0 {
		fmt.Fprint(ctx.out, "\"/>\n")
	}
}
func page_svg(info *RenderConf, fout io.Writer, plist *Path, imginfo *imgInfo) int {
	ctx := &svgContext{
		out:     fout,
		newline: 1,
	}

	var (
		bboxx  float64 = imginfo.Trans.Bb[0] + imginfo.Lmar + imginfo.Rmar
		bboxy  float64 = imginfo.Trans.Bb[1] + imginfo.Tmar + imginfo.Bmar
		origx  float64 = imginfo.Trans.Orig[0] + imginfo.Lmar
		origy  float64 = bboxy - imginfo.Trans.Orig[1] - imginfo.Bmar
		scalex float64 = imginfo.Trans.Scalex / info.Unit
		scaley float64 = -imginfo.Trans.Scaley / info.Unit
	)
	fmt.Fprint(ctx.out, "<?xml version=\"1.0\" standalone=\"no\"?>\n")
	fmt.Fprint(ctx.out, "<!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 20010904//EN\"\n")
	fmt.Fprint(ctx.out, " \"http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd\">\n")
	fmt.Fprintf(ctx.out, "<svg version=\"1.0\" xmlns=\"http://www.w3.org/2000/svg\"\n")
	fmt.Fprintf(ctx.out, " width=\"%.0fpx\" height=\"%.0fpx\" viewBox=\"0 0 %f %f\"\n", bboxx, bboxy, bboxx, bboxy)
	fmt.Fprint(ctx.out, " preserveAspectRatio=\"xMidYMid meet\">\n")
	fmt.Fprint(ctx.out, "<metadata>\n")
	fmt.Fprintf(ctx.out, "Created by vectrace (based on potrace %s), originally written by Peter Selinger 2001-2019, ported by nyorotan 2026\n", Version)
	fmt.Fprint(ctx.out, "</metadata>\n")
	fmt.Fprint(ctx.out, "<g transform=\"")
	if origx != 0 || origy != 0 {
		fmt.Fprintf(ctx.out, "translate(%f,%f) ", origx, origy)
	}
	if info.Angle != 0 {
		fmt.Fprintf(ctx.out, "rotate(%.2f) ", -info.Angle)
	}
	fmt.Fprintf(ctx.out, "scale(%f,%f)", scalex, scaley)
	fmt.Fprint(ctx.out, "\"\n")
	fmt.Fprintf(ctx.out, "fill=\"#%06x\" stroke=\"#%06x\" stroke-width=\"%f\" stroke-linejoin=\"round\">\n", info.Color, info.Color, 0.5*info.Unit)
	if info.Opaque {
		ctx.write_paths_opaque(info, plist)
	} else {
		ctx.write_paths_transparent(info, plist)
	}
	fmt.Fprint(ctx.out, "</g>\n")
	fmt.Fprint(ctx.out, "</svg>\n")
	return 0
}
