// Code generated by cxgo. DO NOT EDIT.

package vectrace

func (bm *Bitmap) Get(x int, y int) bool {
	if uint(x) >= uint(bm.W) || uint(y) >= uint(bm.H) {
		return false
	}
	const bpw = 8 * int(sizeofWord)
	return (bm.Map[int64(y)*int64(bm.Dy)+int64(x/bpw)] & (Word(1) << uint(bpw-1-x%bpw))) != 0
}
func (bm *Bitmap) Put(x int, y int, b bool) {
	if uint(x) >= uint(bm.W) || uint(y) >= uint(bm.H) {
		return
	}
	const bpw = 8 * int(sizeofWord)
	idx := int64(y)*int64(bm.Dy) + int64(x/bpw)
	mask := Word(1) << uint(bpw-1-x%bpw)
	if b {
		bm.Map[idx] |= mask
	} else {
		bm.Map[idx] &= ^mask
	}
}
