// Code generated by cxgo. DO NOT EDIT.

package vectrace

func getsize(dy int, h int) int64 {
	var size int64
	if dy < 0 {
		dy = -dy
	}
	size = int64(dy) * int64(h) * int64(int(sizeofWord))
	if size < 0 || h != 0 && dy != 0 && size/int64(h)/int64(dy) != int64(int(sizeofWord)) {
		return -1
	}
	return size
}
func bm_size(bm *Bitmap) int64 {
	return getsize(bm.Dy, bm.H)
}

// bm_free は Go のガベージコレクションに任せるため不要
func bm_free(bm *Bitmap) {}

func NewBitmap(w int, h int) *Bitmap {
	var (
		bm *Bitmap
		dy int
	)
	if w == 0 {
		dy = 0
	} else {
		dy = (w-1)/(8*(int(sizeofWord))) + 1
	}
	var size int64
	size = getsize(dy, h)
	if size < 0 {
		panic("out of memory")
		return nil
	}
	if size == 0 {
		size = int64(int(sizeofWord))
	}
	bm = new(Bitmap)
	if bm == nil {
		return nil
	}
	bm.W = w
	bm.H = h
	bm.Dy = dy
	bm.Map = make([]Word, uintptr(size)/sizeofWord)
	if bm.Map == nil {

		return nil
	}
	return bm
}
func bm_clear(bm *Bitmap, c int) {
	val := Word(0)
	if c != 0 {
		val = ^Word(0)
	}
	for i := range bm.Map {
		bm.Map[i] = val
	}
}
func bm_dup(bm *Bitmap) *Bitmap {
	var (
		bm1 *Bitmap = NewBitmap(bm.W, bm.H)
		y   int
	)
	if bm1 == nil {
		return nil
	}
	for y = 0; y < bm.H; y++ {
		copy(bm1.Map[int64(y)*int64(bm1.Dy):], bm.Map[int64(y)*int64(bm.Dy):int64(y)*int64(bm.Dy)+int64(bm1.Dy)])
	}
	return bm1
}
func bm_invert(bm *Bitmap) {
	dy := bm.Dy
	if dy < 0 {
		dy = -dy
	}
	for y := 0; y < bm.H; y++ {
		start := int64(y) * int64(bm.Dy)
		for i := 0; i < dy; i++ {
			bm.Map[start+int64(i)] ^= ^Word(0)
		}
	}
}
func bm_resize(bm *Bitmap, h int) int {
	var (
		dy      int = bm.Dy
		newsize int64
		newmap  []Word
	)
	if dy < 0 {
		bm_flip(bm)
	}
	newsize = getsize(dy, h)
	if newsize < 0 {
		panic("out of memory")
		goto error
	}
	if newsize == 0 {
		newsize = int64(int(sizeofWord))
	}
	newmap = make([]Word, uintptr(newsize)/sizeofWord)
	copy(newmap, bm.Map)
	if newmap == nil {
		goto error
	}
	bm.Map = []Word(newmap)
	bm.H = h
	if dy < 0 {
		bm_flip(bm)
	}
	return 0
error:
	if dy < 0 {
		bm_flip(bm)
	}
	return 1
}
