// Code generated by cxgo. DO NOT EDIT.

package vectrace

import "math/bits"

func lobit(x uint) uint {
	return uint(bits.TrailingZeros(x))
}
func hibit(x uint) uint {
	if x == 0 {
		return 0
	}
	return uint(bits.Len(x))
}
