/*
COPYRIGHT

 Copyright (C) 2001-2019 Peter Selinger

	*Modified by nyorotan 2026
		Vectrace is an image tracing tool based on a Go implementation
		of Potrace—a direct machine translation (transpilation) of
		Potrace using cxgo—that converts bitmap images into SVG vector
		graphics with support for color layers.

 The use of the name "Potrace" is governed by a separate policy, see
 TRADEMARKS below.

 This program is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 2 of the License, or (at
 your option) any later version.

 This program is distributed in the hope that it will be useful, but
 WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program; if not, write to the Free Software Foundation,
 Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 See also http://www.gnu.org/.

 See the file LICENSE for details.
*/

package main

import (
	"bytes"
	"fmt"
	"image"
	"image/color"
	_ "image/png"
	"io"
	"math"
	"math/bits"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"

	"golang.org/x/text/language"
	"golang.org/x/text/message"

	_ "golang.org/x/image/bmp"

	"golang.org/x/sync/errgroup"

	"github.com/spf13/cobra"

	"vectrace"
)

var version = "v1.0.1    is based on Potrace  version 1.16"

var Root = &cobra.Command{
	Use:   "vectrace [flags] [filename...]",
	Short: "A tool to trace bitmap images into vector graphics",
	Long: `Vectrace is a Potrace-based image tracing tool that converts
bitmap images into SVG vector graphics with support for color layers.`,
	Version: version,
	RunE:    run,
}

var (
	fOut *string // 出力ファイルパス
	// トレース精度調整用のフラグを追加
	fTurdsize     *int     // 小さなノイズ（スペックル）を除去するサイズ境界
	fTurnpolicy   *int     // パス分解時の分岐方向の決定ポリシー
	fAlphamax     *float64 // 角の丸みを制御するしきい値
	fNoOpticurve  *bool    // 曲線最適化を無効化するかどうか
	fOpttolerance *float64 // 曲線最適化時の許容誤差
	fThreshold    *float64 // 2値化の閾値 (0.0 - 1.0)
	fColorSplit   *bool    // カラー画像を色ごとに分解するか
	fBgDilation   *int     // 白い下地の追加膨張回数
	fLicense      *bool    // ライセンス全文表示フラグ
)

type layerData struct {
	paths  *vectrace.Path
	color  RGB
	area   int
	bm     *vectrace.Bitmap
	isBase bool
}

type colorCluster struct {
	count            int
	sumR, sumG, sumB uint64
	rep              RGB // 代表色（平均値）
}

type RGB struct {
	R, G, B uint8
}

func (c RGB) Hex() int {
	return int(c.R)<<16 | int(c.G)<<8 | int(c.B)
}

func init() {
	// 日本語メッセージの登録
	message.SetString(language.Japanese, "A tool to trace bitmap images into vector graphics", "ビットマップ画像をベクターグラフィックスにトレースするツール")
	message.SetString(language.Japanese, "Vectrace is a Potrace-based image tracing tool that converts \nbitmap images into SVG vector graphics with support for color layers.", "Vectraceは、ビットマップ画像をカラーレイヤー対応のSVGベクターグラフィックスに変換するPotraceベースの画像トレースツールです。")
	message.SetString(language.Japanese, "output file path (only available with a single input source)", "出力ファイルパス（単一入力ソースの場合のみ有効）")
	message.SetString(language.Japanese, "suppress speckles of up to this many pixels", "指定したピクセル数以下のノイズ（スペックル）を除去")
	message.SetString(language.Japanese, "force the base layer (outline) to black", "ベースレイヤー（輪郭）を黒に強制する")
	message.SetString(language.Japanese, "how to resolve ambiguities in path decomposition (0:black, 1:white, 2:left, 3:right, 4:minority, 5:majority, 6:random)", "パス分解時の分岐方向の決定ポリシー (0:黒, 1:白, 2:左, 3:右, 4:少数派, 5:多数派, 6:ランダム)")
	message.SetString(language.Japanese, "corner threshold parameter", "角の丸みを制御するしきい値")
	message.SetString(language.Japanese, "turn off curve optimization", "曲線最適化を無効化する")
	message.SetString(language.Japanese, "curve optimization tolerance", "曲線最適化時の許容誤差")
	message.SetString(language.Japanese, "threshold for digitizing images", "画像の2値化しきい値")
	message.SetString(language.Japanese, "split color image into multiple layers", "カラー画像を複数のレイヤーに分割する")
	message.SetString(language.Japanese, "extra dilation passes for the white background to create an outline", "白い背景にアウトラインを作成するための追加の膨張回数")
	message.SetString(language.Japanese, "display the full license text", "ライセンスの全文を表示する")

	message.SetString(language.Japanese, "the -o/--output flag cannot be used when processing multiple files; outputs will be generated automatically", "複数のファイルを処理する場合、-o/--outputフラグは使用できません。出力は自動的に生成されます")
	message.SetString(language.Japanese, "failed to decode image: %v", "画像のデコードに失敗しました: %v")
	message.SetString(language.Japanese, "image contains more than 256 unique colors, which exceeds the limit for color splitting", "画像に256色を超えるユニークな色が含まれています。これはカラー分解の制限を超えています")
	message.SetString(language.Japanese, "invalid SVG generated by library", "ライブラリによって生成されたSVGが無効です")
	message.SetString(language.Japanese, "tracing failed", "トレースに失敗しました")
	message.SetString(language.Japanese, "tracing incomplete", "トレースが不完全です")
}

var fForceBlack *bool // ベースレイヤーを黒に強制するか

func getPrinter() *message.Printer {
	var prefs []string
	if lang := os.Getenv("LANG"); lang != "" {
		prefs = append(prefs, lang)
	}
	if lc := os.Getenv("LC_ALL"); lc != "" {
		prefs = append(prefs, lc)
	}
	// Windowsの場合のフォールバック
	if runtime.GOOS == "windows" {
		if winLang := getWindowsLocale(); winLang != "" {
			prefs = append(prefs, winLang)
		}
	}

	tag, _ := language.MatchStrings(language.NewMatcher([]language.Tag{
		language.English,
		language.Japanese,
	}), prefs...)
	return message.NewPrinter(tag)
}

func main() {
	p := getPrinter()

	// コマンドの説明文を翻訳
	Root.Short = p.Sprintf("A tool to trace bitmap images into vector graphics")
	Root.Long = p.Sprintf("Vectrace is a Potrace-based image tracing tool that converts \nbitmap images into SVG vector graphics with support for color layers.")

	fOut = Root.Flags().StringP("output", "o", "", p.Sprintf("output file path (only available with a single input source)"))
	// Potrace の標準的なパラメータをフラグとして追加
	fTurdsize = Root.Flags().IntP("turdsize", "t", 2, p.Sprintf("suppress speckles of up to this many pixels"))
	fTurnpolicy = Root.Flags().IntP("turnpolicy", "z", 4, p.Sprintf("how to resolve ambiguities in path decomposition (0:black, 1:white, 2:left, 3:right, 4:minority, 5:majority, 6:random)"))
	fAlphamax = Root.Flags().Float64P("alphamax", "a", 1.0, p.Sprintf("corner threshold parameter"))
	fNoOpticurve = Root.Flags().BoolP("no-opticurve", "n", false, p.Sprintf("turn off curve optimization"))
	fOpttolerance = Root.Flags().Float64P("opttolerance", "O", 0.2, p.Sprintf("curve optimization tolerance"))
	fThreshold = Root.Flags().Float64P("blacklevel", "k", 0.5, p.Sprintf("threshold for digitizing images"))
	fColorSplit = Root.Flags().BoolP("color", "C", false, p.Sprintf("split color image into multiple layers"))
	fForceBlack = Root.Flags().BoolP("force-black", "K", false, p.Sprintf("force the base layer (outline) to black"))
	fBgDilation = Root.Flags().IntP("bg-dilation", "b", -1, p.Sprintf("extra dilation passes for the white background to create an outline"))
	fLicense = Root.Flags().BoolP("license", "l", false, p.Sprintf("display the full license text"))

	if err := Root.Execute(); err != nil {
		os.Exit(1)
	}
}

func run(cmd *cobra.Command, args []string) error {
	p := getPrinter()
	if *fLicense {
		fmt.Println(vectrace.FullLicense)
		return nil
	}

	conf := vectrace.DefaultConfig()
	// フラグの値を Config に反映させる
	conf.TurdSize = *fTurdsize
	conf.TurnPolicy = *fTurnpolicy
	conf.AlphaMax = *fAlphamax
	conf.OptiCurve = !*fNoOpticurve
	conf.OptTolerance = *fOpttolerance

	if len(args) == 0 {
		// 引数がなく、かつ標準入力がターミナルの場合はヘルプを表示して終了する
		stat, _ := os.Stdin.Stat()
		if (stat.Mode() & os.ModeCharDevice) != 0 {
			return cmd.Help()
		}
		return process(*fOut, conf, "-", os.Stdin)
	}

	if len(args) > 1 && *fOut != "" {
		return fmt.Errorf("%s", p.Sprintf("the -o/--output flag cannot be used when processing multiple files; outputs will be generated automatically"))
	}

	// errgroup を使用して並列処理を管理
	g, _ := errgroup.WithContext(cmd.Context())
	g.SetLimit(runtime.NumCPU()) // 同時実行数をCPUスレッド数に基づいて自動設定

	for _, fname := range args {
		fname := fname // ループ変数のキャプチャを防止
		g.Go(func() error {
			f, err := os.Open(fname)
			if err != nil {
				return err
			}
			defer f.Close()

			// 出力先の決定: 引数が1つの場合は -o を尊重し、複数の場合は自動生成する
			outPath := ""
			if len(args) == 1 {
				outPath = *fOut
			}
			return process(outPath, conf, fname, f)
		})
	}

	// 全ての goroutine が完了するのを待ち、最初に発生したエラーを返す
	return g.Wait()
}

func process(out string, conf *vectrace.Config, fname string, r io.Reader) error {
	p := getPrinter()
	// image.Decode はインポートされたデコーダー（PNG, BMP）を使用して画像をデコードします
	img, _, decodeErr := image.Decode(r)
	if decodeErr != nil {
		return fmt.Errorf(p.Sprintf("failed to decode image: %v", decodeErr))
	}

	// カラー分解モードの場合
	if *fColorSplit {
		const colorSimilarityThreshold = 15.0 // 似た色を統合する閾値（値が大きいほど色がまとまる）

		clusters := make(map[RGB]*colorCluster)
		bounds := img.Bounds()

		if paletted, ok := img.(*image.Paletted); ok {
			// 頻度を正確に計算するためにピクセルデータを走査
			idxCounts := make([]int, len(paletted.Palette))
			for _, idx := range paletted.Pix {
				idxCounts[idx]++
			}
			for idx, count := range idxCounts {
				if count == 0 {
					continue
				}
				c := paletted.Palette[idx]
				r, g, b, a := c.RGBA()
				if a < 32768 {
					continue
				} // 透明部分はスキップ
				rgb := RGB{uint8(r >> 8), uint8(g >> 8), uint8(b >> 8)}
				if rgb.R == 255 && rgb.G == 255 && rgb.B == 255 {
					continue
				} // 白はスキップ

				if _, ok := clusters[rgb]; !ok {
					clusters[rgb] = &colorCluster{}
				}
				clusters[rgb].count += count
				clusters[rgb].sumR += uint64(rgb.R) * uint64(count)
				clusters[rgb].sumG += uint64(rgb.G) * uint64(count)
				clusters[rgb].sumB += uint64(rgb.B) * uint64(count)
			}
		} else {
			for y := bounds.Min.Y; y < bounds.Max.Y; y++ {
				for x := bounds.Min.X; x < bounds.Max.X; x++ {
					var rgb RGB
					// image.NRGBA ならアルファ乗算前の生の色を取得できる
					if nrgba, ok := img.(*image.NRGBA); ok {
						c := nrgba.NRGBAAt(x, y)
						if c.A < 128 {
							continue
						}
						rgb = RGB{c.R, c.G, c.B}
					} else {
						// その他の形式（image.RGBAなど）は従来通りだが、aの影響を受ける
						r, g, b, a := img.At(x, y).RGBA()
						if a < 32768 {
							continue
						}
						// アルファ乗算の影響を最小限にするため、16bitから8bitへ
						rgb = RGB{uint8(r >> 8), uint8(g >> 8), uint8(b >> 8)}
					}

					// 既存の色の中に十分近い色があるかチェック（簡易的な量子化）
					foundClose := false
					for existingRGB, cluster := range clusters {
						if colorDistance(rgb, existingRGB) < colorSimilarityThreshold {
							cluster.count++
							cluster.sumR += uint64(rgb.R)
							cluster.sumG += uint64(rgb.G)
							cluster.sumB += uint64(rgb.B)
							foundClose = true
							break
						}
					}

					// 純粋な白色（背景）は新しい色として登録しない
					if rgb.R == 255 && rgb.G == 255 && rgb.B == 255 {
						continue
					}

					if !foundClose {
						clusters[rgb] = &colorCluster{
							count: 1,
							sumR:  uint64(rgb.R),
							sumG:  uint64(rgb.G),
							sumB:  uint64(rgb.B),
						}
					}

					if len(clusters) > 256 {
						return fmt.Errorf(p.Sprintf("image contains more than 256 unique colors, which exceeds the limit for color splitting"))
					}
				}
			}
		}

		// 各カラークラスターの平均色を確定させる
		for _, cluster := range clusters {
			cluster.rep = RGB{uint8(cluster.sumR / uint64(cluster.count)), uint8(cluster.sumG / uint64(cluster.count)), uint8(cluster.sumB / uint64(cluster.count))}
		}

		var colorList []RGB
		for rgb := range clusters {
			colorList = append(colorList, rgb)
		}

		// 各色ごとの Bitmap を一斉に準備
		sz := bounds.Size()
		bitmaps := make([]*vectrace.Bitmap, len(colorList))
		for i := range bitmaps {
			bitmaps[i] = vectrace.NewBitmap(sz.X, sz.Y)
		}

		// 画像を1回だけ走査して全ピクセルを適切な Bitmap に振り分ける
		// これにより O(N*C^2) から O(N*C) へ劇的に高速化
		baseBM := vectrace.NewBitmap(sz.X, sz.Y)
		var baseSumR, baseSumG, baseSumB, baseCount uint64

		if paletted, ok := img.(*image.Paletted); ok {
			// パレットのインデックス -> Bitmapのインデックス の変換テーブルを作成
			baseMapping := make([]bool, len(paletted.Palette))
			mapping := make([]int, len(paletted.Palette))
			for i, c := range paletted.Palette {
				r, g, b, a := c.RGBA()
				// ベースレイヤー（B/W）用の判定
				baseMapping[i] = a >= 32768 && float64(r)+float64(g)+float64(b) <= *fThreshold*3*65535

				if a < 32768 {
					mapping[i] = -1 // スキップ対象
					continue
				}
				mapping[i] = getClosestColorIndex(uint8(r>>8), uint8(g>>8), uint8(b>>8), colorList)
			}

			// Pix スライスを直接走査
			for y := 0; y < sz.Y; y++ {
				rowStart := (bounds.Min.Y + y) * paletted.Stride
				for x := 0; x < sz.X; x++ {
					colorIdx := paletted.Pix[rowStart+(bounds.Min.X+x)]
					if baseMapping[colorIdx] {
						baseBM.Put(x, sz.Y-1-y, true)
						c := paletted.Palette[colorIdx]
						r, g, b, _ := c.RGBA()
						baseSumR += uint64(r >> 8)
						baseSumG += uint64(g >> 8)
						baseSumB += uint64(b >> 8)
						baseCount++
					}
					targetbmIdx := mapping[colorIdx]
					if targetbmIdx >= 0 {
						bitmaps[targetbmIdx].Put(x, sz.Y-1-y, true)
					}
				}
			}
		} else {
			for y := 0; y < sz.Y; y++ {
				for x := 0; x < sz.X; x++ {
					var pr, pg, pb uint8
					r, g, b, a := img.At(bounds.Min.X+x, bounds.Min.Y+y).RGBA()

					// ベースレイヤー（B/W）用の判定
					if a >= 32768 && float64(r)+float64(g)+float64(b) <= *fThreshold*3*65535 {
						baseBM.Put(x, sz.Y-1-y, true)
						baseSumR += uint64(r >> 8)
						baseSumG += uint64(g >> 8)
						baseSumB += uint64(b >> 8)
						baseCount++
					}

					if nrgba, ok := img.(*image.NRGBA); ok {
						c := nrgba.NRGBAAt(bounds.Min.X+x, bounds.Min.Y+y)
						if c.A < 128 {
							continue
						}
						pr, pg, pb = c.R, c.G, c.B
					} else {
						if a < 16384 {
							continue
						}
						pr, pg, pb = uint8(r>>8), uint8(g>>8), uint8(b>>8)
					}

					closestIdx := getClosestColorIndex(pr, pg, pb, colorList)
					// ライブラリの座標系に合わせて Put
					bitmaps[closestIdx].Put(x, sz.Y-1-y, true)
				}
			}
		}

		// ベースレイヤーの色を「閾値内ピクセルの平均」として算出
		var baseColor RGB
		if *fForceBlack {
			baseColor = RGB{0, 0, 0}
		} else if baseCount > 0 {
			baseColor = RGB{uint8(baseSumR / baseCount), uint8(baseSumG / baseCount), uint8(baseSumB / baseCount)}
		}

		// メイン画像全体のシルエット（描画許容範囲）を計算
		silhouetteBM := vectrace.NewBitmap(sz.X, sz.Y)
		for _, bm := range bitmaps {
			for i := range bm.Map {
				silhouetteBM.Map[i] |= bm.Map[i]
			}
		}
		for i := range baseBM.Map {
			silhouetteBM.Map[i] |= baseBM.Map[i]
		}

		// 全レイヤーの情報を収集
		var layers []layerData
		silhouetteArea := countSetPixels(silhouetteBM)

		// 内部的に「白い下地レイヤー」を自動生成
		// 全レイヤーのシルエット (silhouetteBM) をそのまま白の下地として使用します
		if silhouetteArea > 0 {
			// silhouetteBM の内容を新しいビットマップにコピーしてレイヤーに追加
			mBM := vectrace.NewBitmap(sz.X, sz.Y)
			copy(mBM.Map, silhouetteBM.Map)
			// 面積ソートにより、通常これが一番下（最初）に配置されます
			layers = append(layers, layerData{color: RGB{255, 255, 255}, area: silhouetteArea, bm: mBM})
		}

		// ベースレイヤー（閾値によるメイン形状）を一番使用されている色で追加
		if area := countSetPixels(baseBM); area > 0 {
			layers = append(layers, layerData{color: baseColor, area: area, bm: baseBM, isBase: true})
		}

		// 各色のレイヤーを追加
		for i, rgb := range colorList {
			repColor := clusters[rgb].rep
			if area := countSetPixels(bitmaps[i]); area > 0 {
				layers = append(layers, layerData{color: repColor, area: area, bm: bitmaps[i], isBase: false})
			}
		}

		// 1. レイヤーの重なり順をソート (先に記述されたものが背面になる)
		// [白(最背面) -> 黒 -> 他の色(面積順)] の順になるように制御する。
		sort.Slice(layers, func(i, j int) bool {
			cI, cJ := layers[i].color, layers[j].color
			white := RGB{255, 255, 255}

			// 白（背景シルエット）を最背面に固定
			if cI == white {
				return true
			}
			if cJ == white {
				return false
			}

			// ベースレイヤー（輪郭）を白の次に固定
			if layers[i].isBase {
				return true
			}
			if layers[j].isBase {
				return false
			}

			// その他の色は面積の大きい順（降順）
			return layers[i].area > layers[j].area
		})
		// 2 & 3. 隙間埋め処理とトレース処理を並列実行
		g := new(errgroup.Group)

		// 面積比率の基準を「画像全体のピクセル数」から「白い下地（シルエット）の面積」に変更
		denominator := silhouetteArea
		if denominator <= 0 {
			denominator = sz.X * sz.Y // 万が一シルエットが空の場合のセーフガード
		}

		for i := range layers {
			i := i
			g.Go(func() error {
				ratio := float64(layers[i].area) / float64(denominator)
				passes := 1
				if ratio > 0.2 {
					passes = 2
				}
				if ratio > 0.5 {
					passes = 3
				}

				dilationPasses := passes
				if layers[i].color.R == 255 && layers[i].color.G == 255 && layers[i].color.B == 255 {
					dilationPasses += *fBgDilation
				}
				if dilationPasses < 0 {
					dilationPasses = 0
				}

				// 作業用バッファを1つだけ作成して使い回す
				bmSrc := layers[i].bm
				bmTmp := vectrace.NewBitmap(sz.X, sz.Y)

				for p := 0; p < dilationPasses; p++ {
					dilateBitmap(bmSrc, bmTmp)
					bmSrc, bmTmp = bmTmp, bmSrc // ピンポンバッファ
				}
				for p := 0; p < passes; p++ {
					erodeBitmap(bmSrc, bmTmp)
					bmSrc, bmTmp = bmTmp, bmSrc
				}
				layers[i].bm = bmSrc // 最終的な結果をセット

				paths, err := vectrace.Trace(layers[i].bm, conf)
				if err != nil {
					return fmt.Errorf(p.Sprintf(err.Error()))
				}
				layers[i].paths = paths
				return nil
			})
		}
		if err := g.Wait(); err != nil {
			return err
		}
		return renderCombinedSVG(out, fname, layers, img.Bounds().Size())
	}

	// 通常モード (B/W) - しきい値を適用して Bitmap を作成
	bm := vectrace.BitmapFromImage(img, func(c color.Color) bool {
		r, g, b, a := c.RGBA()
		if a < 32768 { // 半透明以上は背景として扱う
			return false
		}
		// 明るさの合計をしきい値と比較 (各色の最大値は 65535)
		return float64(r)+float64(g)+float64(b) <= *fThreshold*3*65535
	})
	return traceAndRender(out, conf, fname, bm, vectrace.NewRenderConf())
}

// colorDistance は2つの色間の知覚的な距離を計算します
func colorDistance(c1, c2 RGB) float64 {
	dr := float64(c1.R) - float64(c2.R)
	dg := float64(c1.G) - float64(c2.G)
	db := float64(c1.B) - float64(c2.B)
	// 人間の目の感度に基づいた重み付け (Luma approximation)
	return math.Sqrt(dr*dr*0.299 + dg*dg*0.587 + db*db*0.114)
}

// getClosestColorIndex は指定された色に最も近いパレット内の色のインデックスを返します。
func getClosestColorIndex(r, g, b uint8, palette []RGB) int {
	var minDist float64 = math.MaxFloat64
	var closestIdx int
	current := RGB{r, g, b}

	for i, target := range palette {
		dist := colorDistance(current, target)
		if dist < minDist {
			minDist = dist
			closestIdx = i
		}
		if dist == 0 {
			return i
		} // 完全一致
	}
	return closestIdx
}

// countSetPixels はビットマップ内で塗りつぶされているピクセル数をカウントします
func countSetPixels(bm *vectrace.Bitmap) int {
	count := 0
	for _, v := range bm.Map {
		count += bits.OnesCount(uint(v))
	}
	return count
}

// dilateBitmap はビットマップを1ピクセル膨張させます
func dilateBitmap(src, dst *vectrace.Bitmap) {
	dy := src.Dy // 1行あたりのワード数
	bitS := uint(bits.UintSize - 1)

	for y := 0; y < src.H; y++ {
		off := y * dy
		for i := 0; i < dy; i++ {
			curr := src.Map[off+i]

			// 左右方向の膨張（ビットシフト）
			// Potraceのビット順序: MSB(左) -> LSB(右)
			res := curr | (curr << 1) | (curr >> 1)

			// 隣接ワードからの回り込み処理
			if i > 0 {
				res |= (src.Map[off+i-1] & 1) << bitS // 左ワードの右端が、自ワードの左端へ
			}
			if i < dy-1 {
				res |= (src.Map[off+i+1] >> bitS) // 右ワードの左端が、自ワードの右端へ
			}

			// 上下方向の膨張（境界チェック付き）
			if y > 0 {
				res |= src.Map[off-dy+i]
			}
			if y < src.H-1 {
				res |= src.Map[off+dy+i]
			}

			dst.Map[off+i] = res
		}
	}
}

// erodeBitmap はビットマップを1ピクセル収縮させます
func erodeBitmap(src, dst *vectrace.Bitmap) {
	dy := src.Dy
	bitS := uint(bits.UintSize - 1)

	for y := 0; y < src.H; y++ {
		off := y * dy
		for i := 0; i < dy; i++ {
			curr := src.Map[off+i]
			if curr == 0 {
				dst.Map[off+i] = 0 // バッファ再利用のため明示的にクリア
				continue
			}

			// 左右方向の収縮
			// 左隣のピクセル情報 (bit n+1 を現在の位置 n に持ってくる)
			lNeighbor := curr >> 1
			if i > 0 {
				lNeighbor |= (src.Map[off+i-1] & 1) << bitS
			} else {
				lNeighbor |= (1 << bitS) // 画像の端は削らないよう黒とみなす
			}

			// 右隣のピクセル情報 (bit n-1 を現在の位置 n に持ってくる)
			rNeighbor := curr << 1
			if i < dy-1 {
				rNeighbor |= (src.Map[off+i+1] >> bitS)
			} else {
				rNeighbor |= 1 // 画像の端は削らないよう黒とみなす
			}

			res := curr & lNeighbor & rNeighbor

			// 上下方向の収縮
			if y > 0 {
				res &= src.Map[off-dy+i]
			}

			if y < src.H-1 {
				res &= src.Map[off+dy+i]
			}

			dst.Map[off+i] = res
		}
	}
}

// renderCombinedSVG は複数の色レイヤーを1つのSVGファイルに合成して出力します
func renderCombinedSVG(out, fname string, layers []layerData, size image.Point) error {
	p := getPrinter()
	var combinedSVG bytes.Buffer

	for i, layer := range layers {
		renderConf := vectrace.NewRenderConf()
		renderConf.Color = layer.color.Hex()

		var buf bytes.Buffer
		if err := vectrace.Render("svg", renderConf, &buf, layer.paths, size.X, size.Y); err != nil {
			return fmt.Errorf(p.Sprintf(err.Error()))
		}

		svgStr := buf.String()
		if i == 0 {
			// 最初のレイヤーからヘッダーと最初のグループを取得
			endIdx := strings.LastIndex(svgStr, "</svg>")
			if endIdx == -1 {
				return fmt.Errorf(p.Sprintf("invalid SVG generated by library"))
			}
			combinedSVG.WriteString(svgStr[:endIdx])
		} else {
			// 2番目以降のレイヤーからは <g ...> </g> の部分だけを抽出して追加
			startIdx := strings.Index(svgStr, "<g transform=")
			endIdx := strings.LastIndex(svgStr, "</g>")
			if startIdx != -1 && endIdx != -1 {
				combinedSVG.WriteString(svgStr[startIdx : endIdx+4])
				combinedSVG.WriteString("\n")
			}
		}
	}
	combinedSVG.WriteString("</svg>\n")

	// 出力先の決定
	finalOut := out
	if finalOut == "" {
		if fname == "-" {
			fmt.Print(combinedSVG.String())
			return nil
		}
		finalOut = strings.TrimSuffix(fname, filepath.Ext(fname)) + ".svg"
	}

	if finalOut == "-" {
		fmt.Print(combinedSVG.String())
		return nil
	}

	return os.WriteFile(finalOut, combinedSVG.Bytes(), 0644)
}

func traceAndRender(out string, conf *vectrace.Config, fname string, bm *vectrace.Bitmap, c *vectrace.RenderConf) error {
	p := getPrinter()
	paths, err := vectrace.Trace(bm, conf)
	if err != nil {
		return fmt.Errorf(p.Sprintf(err.Error()))
	}

	if out == "-" || (out == "" && fname == "-") {
		return vectrace.Render("svg", c, os.Stdout, paths, bm.W, bm.H)
	}
	if out == "" {
		ext := filepath.Ext(fname)
		out = strings.TrimSuffix(fname, ext)
		out += ".svg"
	}
	return vectrace.RenderFile("svg", c, out, paths, bm.W, bm.H)
}
